# Generated by Django 3.2.9 on 2022-02-08 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_cell'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('task', 'start_datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'user')},
        ),
    ]
